# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# FORMAT PROMPT
### format = '''
### [┌── ](drawings)$env_var$username$hostname$localip$directory$git_branch$git_commit$git_status$git_metrics$battery$container$docker_context$c$rust$golang$python$nodejs$java$php$dotnet$elixir$erlang$gcloud$kubernetes$aws$package$fill$cmd_duration$memory_usage[─┐ ](drawings)
### [└─ ](drawings)$sudo$character
### '''
### right_format = '''
### $time[─┘](drawings)
### '''

format = '''
$username$hostname$localip$os$directory$git_branch$git_commit$git_status$container$c$rust$golang$python$nodejs$java$php$dotnet$elixir$erlang$gcloud$kubernetes$aws$package$docker_context$terraform$fill$memory_usage
$nix_shell$sudo$character
'''
right_format = '''$cmd_duration$jobs'''

continuation_prompt = "➜"
add_newline = true
scan_timeout = 10
palette = 'main'

[palettes.main] # main style
blue = '21'
cyan = '51'
green = '118'
red = '196'
orange = '208'
drawings = '001'

[env_var.STARSHIP_DISTRO]
format = '[$env_value](bold white) '
variable = "STARSHIP_DISTRO"
disabled = false

[battery] # battery module
format = '[$symbol$percentage]($style) '
disabled = false

[c] # C module
format = '[$symbol]($style) '
symbol = 'C'
style = 'bold blue'

[character] # Return value indicator
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'
vimcmd_symbol = '[](blue)'
vimcmd_replace_one_symbol = '[](orange)'
vimcmd_replace_symbol = '[](red)'
vimcmd_visual_symbol = '[](purple)'

[cmd_duration] # Command duration
min_time = 500
# format = '[\[](drawings)[$duration]($style)[\]─](drawings)'
format = ' [$duration]($style)'
style = 'bold yellow'
show_milliseconds = false

[container]
format = '[$symbol \[$name\]]($style) '

[directory] # Directory
format = '[ $path]($style)[$read_only]($read_only_style) '
truncation_length = 3

[docker_context] # Docker
format = '[\[$symbol $context\] ]($style) '
symbol = ''

[fill] # Fill
symbol = " "
style = "drawings"
disabled = false

[git_branch] # Git branch
format = 'on [$symbol git::$branch]($style)'
symbol = ''
style = 'bold yellow'

[git_commit] # Git commit
format = ' commit: [$hash$tag]($style)'
style = 'bold yellow'
tag_symbol = ' '
tag_disabled = false

[git_metrics] # Git metrics
added_style = 'bold green'
deleted_style = 'bold red'
only_nonzero_diffs = true
format = '[+$added]($added_style)[-$deleted]($deleted_style) '
disabled = false

[git_status] # Git status
format = '[$all_status$ahead_behind]($style) '
style = 'bold yellow'

[hostname] # Hostname
ssh_only = true
format = ' on [$hostname]($style)'
style = 'bold green'

[jobs] # Jobs
format = ' [\[$number\]]($style)'
style = 'orange'
number_threshold = 1

[line_break] # Line break
disabled = false

[localip] # Local IP
ssh_only = true
disabled = false
format = ''' [\[$localipv4\]]($style)
'''
style = 'bold blue'

[memory_usage]
disabled = false
format = '[\[$symbol$ram\($ram_pct\)\]]($style)'
threshold = 75
symbol = ' '
style = "bold dimmed green"

[nix_shell] # Nix shell
format = '[$symbol$state-$name]($style) '
symbol = ' '
style = 'bold blue'

[nodejs] # NodeJS
format = '[$symbol]($style) '
symbol = ''
version_format = 'v${major}'
style = 'bold green'

[os] # OS
format = '[$symbol ]($style)'
style = 'bold white'
disabled = false

[os.symbols] # OS symbol
Windows = ''
Linux = ''
Macos = ''
Raspbian = ''
Debian = ''
Ubuntu = ''
Arch = ''
Manjaro = ''
Fedora = ''
CentOS = ''
Alpine = ''
NixOS = ''
Redhat = ''

[package] # Package
disabled = false
format = '[\[$symbol$version\]]($style) '
style = 'dimmed orange'
version_format = '${raw}'
symbol = ' '
display_private = true

[python] # Python
format = '[$symbol]($style) '
symbol = ''
style = 'bold blue'

[rust] # Rust
format = '[$symbol]($style) '
symbol = ''
style = 'bold orange'

[shell] # Shell
format = '[$indicator]($style) '
style = 'bold green'
disabled = true

[status] # Status
disabled = false
format = '[$symbol$status]($style) '

[sudo] # Sudo
format = '[$symbol]($style) '
symbol = '#'
style = 'bold red'
disabled = false

[terraform] # Terraform
format = '[$symbol$workspace]($style) '
symbol = '󱁢 '
style = 'bold 105'
disabled = false
version_format = 'v${raw}'

[time] # Time
format = '[\[](drawings)[$time]($style)[\]](drawings)'
style = 'bold orange'
disabled = false
time_format = '%a %d-%H:%M'

[username] # Username
format = '[$user]($style)'
style_user = 'bold orange'
style_root = 'bold red'
